# left bar
title = "instantiator.dev"
author = "Lewis Westbury" # goes in page titles
description = "tech, volunteers, public safety, articles and ideas"
profilePicture = "/lewis/profile.jpg"
favicon = "favicons/"
keywords = ""
# copyright = "2020-2021"

customCss = [] # example ["css/custom.css"]
customJs = [] # example ["js/custom.js"]

mainSections = ["post"]
images = ["/lewis/default-image.png"]
doNotLoadAnimations = false

# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"

# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

singleDateFormat = "2006-01-02"
indexDateFormat = "2006-01-02"
listDateFormat = "2006-01-02"

# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/instantiator"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/instantiator"

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/lewiswestbury"

[[socialIcons]]
icon = "fas fa-globe"
title = "Police Rewired"
url = "https://policerewired.org"
